In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/kaggle_data.csv")

In [ ]:
df.head()
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   object
 1   Segment       9994 non-null   object
 2   Country       9994 non-null   object
 3   City          9994 non-null   object
 4   State         9994 non-null   object
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   object
 7   Category      9994 non-null   object
 8   Sub-Category  9994 non-null   object
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1015.1+ KB

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [ ]:
df = df.drop_duplicates()

In [ ]:
df[["Sales", "Profit", "Quantity", "Discount"]].describe()

              Sales      Profit     Quantity     Discount
count   9977.000000  9977.00000  9977.000000  9977.000000
mean     230.148902    28.69013     3.790719     0.156278
std      623.721409   234.45784     2.226657     0.206455
min        0.444000 -6599.97800     1.000000     0.000000
25%       17.300000     1.72620     2.000000     0.000000
50%       54.816000     8.67100     3.000000     0.200000
75%      209.970000    29.37200     5.000000     0.200000
max    22638.480000  8399.97600    14.000000     0.800000

In [ ]:
df.to_csv("superstore_cleaned.csv", index=False)

In [ ]:
region_analysis = df.groupby("Region")[["Sales", "Profit"]].sum()
region_analysis

               Sales       Profit
Region
Central  500782.8528   39655.8752
East     678435.1960   91506.3092
South    391721.9050   46749.4303
West     725255.6365  108329.8079

In [ ]:
region_analysis = region_analysis.sort_values(by="Sales", ascending=False)
region_analysis

               Sales       Profit
Region
West     725255.6365  108329.8079
East     678435.1960   91506.3092
Central  500782.8528   39655.8752
South    391721.9050   46749.4303

In [ ]:
category_sales = df.groupby("Category")["Sales"].sum().sort_values(ascending=False)
category_sales

Category
Technology         836154.0330
Furniture          741306.3133
Office Supplies    718735.2440
Name: Sales, dtype: float64

In [ ]:
df.groupby("Discount")["Profit"].mean()

Discount
0.00     67.024108
0.10     96.055074
0.15     27.288298
0.20     24.721217
0.30    -45.828401
0.32    -88.560656
0.40   -111.927429
0.45   -226.646464
0.50   -310.703456
0.60    -43.077212
0.70    -95.874060
0.80   -102.116395
Name: Profit, dtype: float64

In [ ]:
df.groupby("Segment")["Sales"].sum()

Segment
Consumer       1.160833e+06
Corporate      7.060701e+05
Home Office    4.292927e+05
Name: Sales, dtype: float64

In [ ]:
df.groupby("Sub-Category")["Profit"].sum().sort_values()

Sub-Category
Tables        -17725.4811
Bookcases      -3472.5560
Supplies       -1189.0995
Fasteners        949.5182
Machines        3384.7569
Labels          5526.3820
Art             6524.6118
Envelopes       6964.1767
Furnishings    13052.7230
Appliances     18138.0054
Storage        21278.8264
Chairs         26567.1278
Binders        30228.0003
Paper          33944.2395
Accessories    41936.6357
Phones         44515.7306
Copiers        55617.8249
Name: Profit, dtype: float64